# Generated by Django 3.2.21 on 2023-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compare_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_1', models.CharField(max_length=500)),
                ('filename_2', models.CharField(max_length=500)),
                ('face_distance', models.FloatField()),
                ('tolerance', models.FloatField()),
                ('result', models.BooleanField()),
                ('message', models.TextField(blank=True, null=True)),
                ('exec_time', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='liveness_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('score', models.FloatField()),
                ('result', models.BooleanField()),
                ('message', models.TextField(blank=True, null=True)),
                ('exec_time', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
